# STAGE 1
# ==== CONFIGURE =====
# Use a Node 22 base image
FROM node:22.17.0-bullseye-slim AS build
# Set the working directory to /app inside the container
WORKDIR /app
# Установим pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate
# Скопируем только package.json и pnpm-lock.yaml для кеша зависимостей
COPY frontend/package.json frontend/pnpm-lock.yaml ./
# Установим зависимости
RUN pnpm install --frozen-lockfile
# Скопируем остальные файлы приложения
COPY frontend/. .
# ==== BUILD =====
RUN pnpm run build

# STAGE 2
FROM node:22.17.0-bullseye-slim
WORKDIR /app
COPY --from=build /app/build ./build
RUN npm install -g serve
# ==== RUN =======
# Expose the port on which the app will be running (3000 is the default that `serve` uses)
EXPOSE 3000
# Start the app
CMD [ "serve", "-s", "build" ]